//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormNavKiller {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormNavKiller.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppData Directory.
        /// </summary>
        internal static string appDataStr {
            get {
                return ResourceManager.GetString("appDataStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning Cache for.
        /// </summary>
        internal static string clearCacheStr {
            get {
                return ResourceManager.GetString("clearCacheStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning Session Data for.
        /// </summary>
        internal static string clearSessionDataStr {
            get {
                return ResourceManager.GetString("clearSessionDataStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Directory: .
        /// </summary>
        internal static string delDirStr {
            get {
                return ResourceManager.GetString("delDirStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file: .
        /// </summary>
        internal static string delFileStr {
            get {
                return ResourceManager.GetString("delFileStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories Deleted.
        /// </summary>
        internal static string dirDelStr {
            get {
                return ResourceManager.GetString("dirDelStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string doneStr {
            get {
                return ResourceManager.GetString("doneStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files Deleted.
        /// </summary>
        internal static string fileDelStr {
            get {
                return ResourceManager.GetString("fileDelStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill Program.
        /// </summary>
        internal static string killStr {
            get {
                return ResourceManager.GetString("killStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Not Running ....
        /// </summary>
        internal static string procNotFound {
            get {
                return ResourceManager.GetString("procNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty the RecycleBin failed.
        /// </summary>
        internal static string RBCleanBadStr {
            get {
                return ResourceManager.GetString("RBCleanBadStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Recycle bin.
        /// </summary>
        internal static string RBCleanBtnStr {
            get {
                return ResourceManager.GetString("RBCleanBtnStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty the RecycleBin successsfully.
        /// </summary>
        internal static string RBCleanOkStr {
            get {
                return ResourceManager.GetString("RBCleanOkStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete all items in recycle bin.
        /// </summary>
        internal static string RBCleanStr {
            get {
                return ResourceManager.GetString("RBCleanStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle Bin Count.
        /// </summary>
        internal static string recycleBinCountStr {
            get {
                return ResourceManager.GetString("recycleBinCountStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string restart {
            get {
                return ResourceManager.GetString("restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open download site for : .
        /// </summary>
        internal static string UnableOpenSite {
            get {
                return ResourceManager.GetString("UnableOpenSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
